const TYPES = {
  FETCH_CLUSTERS: 'FETCH_CLUSTERS',
  FETCH_CLUSTERS_SUCCESS: 'FETCH_CLUSTERS_SUCCESS',
  FETCH_CLUSTERS_FAILURE: 'FETCH_CLUSTERS_FAILURE',
  SET_CLUSTER: 'SET_CLUSTER',

  FETCH_SERVICES: 'FETCH_SERVICES',
  FETCH_SERVICES_SUCCESS: 'FETCH_SERVICES_SUCCESS',
  FETCH_SERVICES_FAILURE: 'FETCH_SERVICES_FAILURE',

  FETCH_SERVICE: 'FETCH_SERVICE',
  FETCH_SERVICE_SUCCESS: 'FETCH_SERVICE_SUCCESS',
  FETCH_SERVICE_FAILURE: 'FETCH_SERVICE_FAILURE',

  FETCH_SERVICE_DETAIL: 'FETCH_SERVICE_DETAIL',
  FETCH_SERVICE_DETAIL_SUCCESS: 'FETCH_SERVICE_DETAIL_SUCCESS',
  FETCH_SERVICE_DETAIL_FAILURE: 'FETCH_SERVICE_DETAIL_FAILURE',
  SET_SERVICE: 'SET_SERVICE',

  FETCH_VERSIONS: 'FETCH_VERSIONS',
  FETCH_VERSIONS_SUCCESS: 'FETCH_VERSIONS_SUCCESS',
  FETCH_VERSIONS_FAILURE: 'FETCH_VERISONS_FAILURE',
  SET_VERSION: 'SET_VERSION',

  CREATE_DEPLOYMENT: 'CREATE_DEPLOYMENT',
  CREATE_DEPLOYMENT_SUCCESS: 'CREATE_DEPLOYMENT_SUCCESS',
  CREATE_DEPLOYMENT_FAILURE: 'CREATE_DEPLOYMENT_FAILURE',
};

export default TYPES;
